### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by carlastabile** [xing/beetle#62]
Hey, can you guys create a CHANGELOG? it'd make much easier to see the changes on the gem. 

Thanks! 😄

**Comment by boosty** [comment]
Hi @carlastabile,

there is one at https://github.com/xing/beetle/blob/master/RELEASE_NOTES.rdoc 😉 

I will add a link to the README.

**Comment by boosty** [comment]
https://github.com/xing/beetle/commit/2d134be34397c4f747bfab6eaa253c7fabb62857
